import { Inter } from "next/font/google";
import "../../globals.css";
import * as React from "react";
import Nav from "../../../components/Nav";
import WellContextProvider from "../../../context/WellContextProvider";
import CreatePipeFormContextProvider from "../../../context/CreatePipeFormContextProvider";
import { Toaster } from "@/components/ui/toaster";
import DataContextProvider from "@/context/DataContextProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <div className="">
        <Nav />
        {children}
      </div>
  );
}
